# Generated by Django 5.0.6 on 2024-07-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0002_alter_product_image_url_alter_product_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Zara', max_length=50),
            preserve_default=False,
        ),
    ]
