# Generated by Django 5.0.6 on 2024-07-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0003_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
